on:
  push:
    branches:
      - main

jobs:
  test-package-on-3-13-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Install Python 3.13"
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: "Install tox for running tests"
        run: pip install tox
      - name: "run unit tests with tox"
        run: tox run